# fly.toml app configuration file generated for qs-papers-citations-interactive on 2025-04-23T19:33:48+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'qs-papers-citations-interactive'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
